import type { Metadata } from "next";
import "./globals.css";
import SnackbarProvider from "./snackbarProvider";

export const metadata: Metadata = {
  title: "Rupam Sen",
  description: "Generated by create next app",
  icons: "./r.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <SnackbarProvider>{children}</SnackbarProvider>
      </body>
    </html>
  );
}
